version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Ziad1234
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - OurNetworks-App
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S localhost -U sa -P Ziad1234 -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 3


  hahnleaveabsencemanagementbackend:
    build:
      context: ./HahnLeaveAbsenceManagementBackend
    ports:
      - "4000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=HahnLeaveAbsenceManagementBackendDb;User Id=sa;Password=Ziad1234;MultipleActiveResultSets=True;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    networks:
      - OurNetworks-App


networks:
  OurNetworks-App:
    driver: bridge