
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - SA_PASSWORD=${SA_PASSWORD:-Ziad1234}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - OurNetworks-App
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/127.0.0.1/1433'"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  hahnleaveabsencemanagementbackend:
    build:
      context: ./HahnLeaveAbsenceManagementBackend
    ports:
      - "4000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=HahnLeaveAbsenceManagementBackendDb;User Id=sa;Password=Ziad1234;MultipleActiveResultSets=True;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    networks:
      - OurNetworks-App


networks:
  OurNetworks-App:
    driver: bridge


volumes:
  sqlserver_data:
