// <auto-generated />
using System;
using HahnLeaveAbsenceManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HahnLeaveAbsenceManagement.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250829211911_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HahnLeaveAbsenceManagement.Domain.LeaveRequest.LeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BusinessDays")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LeaveRequests", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d82c532e-7d1a-48b8-ac9d-324d6b625dcc"),
                            BusinessDays = 2,
                            Description = "",
                            EndDate = new DateTime(2025, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 0,
                            UserId = new Guid("e8b8f1f5-85a8-adb8-01a7-17783f381411")
                        },
                        new
                        {
                            Id = new Guid("d6724145-cc1d-9de0-f0b1-e3536194baf5"),
                            BusinessDays = 1,
                            Description = "",
                            EndDate = new DateTime(2025, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 0,
                            UserId = new Guid("e8b8f1f5-85a8-adb8-01a7-17783f381411")
                        },
                        new
                        {
                            Id = new Guid("40015c8b-5d97-9b4f-54ed-23c786c39f44"),
                            BusinessDays = 1,
                            Description = "",
                            EndDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 0,
                            UserId = new Guid("e8b8f1f5-85a8-adb8-01a7-17783f381411")
                        },
                        new
                        {
                            Id = new Guid("71e37e6d-a15c-f71c-da91-022f4b5ce6d9"),
                            BusinessDays = 3,
                            Description = "",
                            EndDate = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Type = 0,
                            UserId = new Guid("10ddb1bd-7956-9c97-a82b-28edd1c8ccd2")
                        },
                        new
                        {
                            Id = new Guid("5e3459e3-58d1-b74b-b105-87d329d945ed"),
                            BusinessDays = 2,
                            Description = "",
                            EndDate = new DateTime(2025, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Type = 1,
                            UserId = new Guid("10ddb1bd-7956-9c97-a82b-28edd1c8ccd2")
                        },
                        new
                        {
                            Id = new Guid("55009f39-77da-87a5-5874-f776a37e2ee9"),
                            BusinessDays = 2,
                            Description = "",
                            EndDate = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 2,
                            UserId = new Guid("10ddb1bd-7956-9c97-a82b-28edd1c8ccd2")
                        },
                        new
                        {
                            Id = new Guid("6d0cafb4-7233-4778-c7c6-7d6db9f4d7a1"),
                            BusinessDays = 5,
                            Description = "",
                            EndDate = new DateTime(2025, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Type = 1,
                            UserId = new Guid("c298b7fb-4152-0102-2e7b-d22eef00e52d")
                        },
                        new
                        {
                            Id = new Guid("21f3c03d-58e2-93e2-f6b4-eac22895e8a2"),
                            BusinessDays = 2,
                            Description = "",
                            EndDate = new DateTime(2025, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 0,
                            UserId = new Guid("c298b7fb-4152-0102-2e7b-d22eef00e52d")
                        },
                        new
                        {
                            Id = new Guid("b5cf61ec-ec4a-d6f0-463f-62b38f4b87a2"),
                            BusinessDays = 4,
                            Description = "",
                            EndDate = new DateTime(2025, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 1,
                            UserId = new Guid("c298b7fb-4152-0102-2e7b-d22eef00e52d")
                        },
                        new
                        {
                            Id = new Guid("d380bc92-c66f-b9a5-eadb-efa05e226d49"),
                            BusinessDays = 5,
                            Description = "",
                            EndDate = new DateTime(2025, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 0,
                            UserId = new Guid("6998a4fe-7fc2-590e-616d-4ad24a81a6db")
                        },
                        new
                        {
                            Id = new Guid("af6db838-9a1d-29b8-9ec9-54e02ede3519"),
                            BusinessDays = 2,
                            Description = "",
                            EndDate = new DateTime(2025, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 0,
                            UserId = new Guid("6998a4fe-7fc2-590e-616d-4ad24a81a6db")
                        },
                        new
                        {
                            Id = new Guid("3cf26427-c262-15b2-73f2-86a008306876"),
                            BusinessDays = 2,
                            Description = "",
                            EndDate = new DateTime(2024, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 1,
                            UserId = new Guid("6998a4fe-7fc2-590e-616d-4ad24a81a6db")
                        },
                        new
                        {
                            Id = new Guid("858d04c3-0272-6dca-d4f7-c428fc00ee5f"),
                            BusinessDays = 3,
                            Description = "",
                            EndDate = new DateTime(2025, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 2,
                            UserId = new Guid("35a56cc6-18e2-2e49-3239-5c878db167bc")
                        },
                        new
                        {
                            Id = new Guid("f49d5baf-7ba6-ee9d-83ef-0bc9cf7a9ec7"),
                            BusinessDays = 5,
                            Description = "",
                            EndDate = new DateTime(2025, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 0,
                            UserId = new Guid("35a56cc6-18e2-2e49-3239-5c878db167bc")
                        },
                        new
                        {
                            Id = new Guid("c6d763d2-c5e6-7fae-8c06-03b9dbd42bf0"),
                            BusinessDays = 3,
                            Description = "",
                            EndDate = new DateTime(2024, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 2,
                            UserId = new Guid("35a56cc6-18e2-2e49-3239-5c878db167bc")
                        },
                        new
                        {
                            Id = new Guid("681e6113-e817-d27f-9ee6-53dc45627751"),
                            BusinessDays = 2,
                            Description = "",
                            EndDate = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Type = 2,
                            UserId = new Guid("901436a1-5810-6631-74fd-382120a6441b")
                        },
                        new
                        {
                            Id = new Guid("099fca96-169d-8434-84ad-c5db6c657356"),
                            BusinessDays = 2,
                            Description = "",
                            EndDate = new DateTime(2025, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 0,
                            UserId = new Guid("901436a1-5810-6631-74fd-382120a6441b")
                        },
                        new
                        {
                            Id = new Guid("4be74fd0-d8ed-6169-c818-e0f85c649444"),
                            BusinessDays = 4,
                            Description = "",
                            EndDate = new DateTime(2025, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 0,
                            UserId = new Guid("901436a1-5810-6631-74fd-382120a6441b")
                        },
                        new
                        {
                            Id = new Guid("8b672f4e-433b-e81a-e434-c602ee8417b2"),
                            BusinessDays = 4,
                            Description = "",
                            EndDate = new DateTime(2025, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 0,
                            UserId = new Guid("5815c2a8-ad8d-03a6-a265-18f65c4882cc")
                        },
                        new
                        {
                            Id = new Guid("79bfb531-45d9-e2db-50f9-ba0aa2430abf"),
                            BusinessDays = 3,
                            Description = "",
                            EndDate = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 0,
                            UserId = new Guid("5815c2a8-ad8d-03a6-a265-18f65c4882cc")
                        },
                        new
                        {
                            Id = new Guid("32e4ba2d-52d5-8732-8db2-c1d7e14650ad"),
                            BusinessDays = 1,
                            Description = "",
                            EndDate = new DateTime(2025, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 0,
                            UserId = new Guid("5815c2a8-ad8d-03a6-a265-18f65c4882cc")
                        },
                        new
                        {
                            Id = new Guid("def128f6-ad9a-1140-bed5-e9db8c6c81f8"),
                            BusinessDays = 2,
                            Description = "",
                            EndDate = new DateTime(2025, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 1,
                            UserId = new Guid("8e91a67b-8c05-e6b5-8801-02477295103f")
                        },
                        new
                        {
                            Id = new Guid("a2b9402b-5443-0b15-c2f6-33c7b672cbcc"),
                            BusinessDays = 3,
                            Description = "",
                            EndDate = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Type = 1,
                            UserId = new Guid("8e91a67b-8c05-e6b5-8801-02477295103f")
                        },
                        new
                        {
                            Id = new Guid("0fd9aa2e-2384-104a-6760-b25b4f591102"),
                            BusinessDays = 4,
                            Description = "",
                            EndDate = new DateTime(2024, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 0,
                            UserId = new Guid("8e91a67b-8c05-e6b5-8801-02477295103f")
                        },
                        new
                        {
                            Id = new Guid("788f62fa-0dde-ce2f-f0ba-9f33f2ebf9ed"),
                            BusinessDays = 3,
                            Description = "",
                            EndDate = new DateTime(2025, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Type = 2,
                            UserId = new Guid("46199b05-5208-7a6e-96a1-b1fa675af8aa")
                        },
                        new
                        {
                            Id = new Guid("b7ac52b4-a393-2088-0636-2e113d78fecc"),
                            BusinessDays = 3,
                            Description = "",
                            EndDate = new DateTime(2025, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 0,
                            UserId = new Guid("46199b05-5208-7a6e-96a1-b1fa675af8aa")
                        },
                        new
                        {
                            Id = new Guid("5772cf27-e19a-34bb-4bde-bf4210b3e191"),
                            BusinessDays = 5,
                            Description = "",
                            EndDate = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 2,
                            UserId = new Guid("46199b05-5208-7a6e-96a1-b1fa675af8aa")
                        },
                        new
                        {
                            Id = new Guid("b821d0c1-ea29-3fae-ad8a-2b06a03fded0"),
                            BusinessDays = 3,
                            Description = "",
                            EndDate = new DateTime(2025, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Type = 2,
                            UserId = new Guid("ed667da6-b4f7-3881-3cd6-96c44c15e821")
                        },
                        new
                        {
                            Id = new Guid("52b8fafa-2b49-e765-8d62-fedf0aa81459"),
                            BusinessDays = 2,
                            Description = "",
                            EndDate = new DateTime(2025, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 1,
                            UserId = new Guid("ed667da6-b4f7-3881-3cd6-96c44c15e821")
                        },
                        new
                        {
                            Id = new Guid("ca4ecb07-c0c9-b812-96d1-92bcd8e0e5fa"),
                            BusinessDays = 2,
                            Description = "",
                            EndDate = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 1,
                            UserId = new Guid("ed667da6-b4f7-3881-3cd6-96c44c15e821")
                        },
                        new
                        {
                            Id = new Guid("edca6b22-c94a-e69f-e3c0-71e1fa383371"),
                            BusinessDays = 1,
                            Description = "",
                            EndDate = new DateTime(2025, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 0,
                            UserId = new Guid("75b52741-41e2-640a-cac3-2a2a63457b4e")
                        },
                        new
                        {
                            Id = new Guid("97c07f4c-c246-0bbe-4c95-0cad44a6c68c"),
                            BusinessDays = 5,
                            Description = "",
                            EndDate = new DateTime(2025, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 1,
                            UserId = new Guid("75b52741-41e2-640a-cac3-2a2a63457b4e")
                        },
                        new
                        {
                            Id = new Guid("d8e7f50d-c4f1-89c1-9396-70003be68ff1"),
                            BusinessDays = 5,
                            Description = "",
                            EndDate = new DateTime(2025, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 2,
                            UserId = new Guid("75b52741-41e2-640a-cac3-2a2a63457b4e")
                        },
                        new
                        {
                            Id = new Guid("73c53d02-dfb3-49fd-4f7c-f4f028aae933"),
                            BusinessDays = 2,
                            Description = "",
                            EndDate = new DateTime(2025, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Type = 1,
                            UserId = new Guid("84ad3fd0-1151-9e9a-71dc-3eaf99e4bdbb")
                        },
                        new
                        {
                            Id = new Guid("b47be7e3-2dab-5d8c-50ab-82306e6d8a3d"),
                            BusinessDays = 5,
                            Description = "",
                            EndDate = new DateTime(2025, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 0,
                            UserId = new Guid("84ad3fd0-1151-9e9a-71dc-3eaf99e4bdbb")
                        },
                        new
                        {
                            Id = new Guid("999233c5-2d92-9ee4-e627-d9a6d813d827"),
                            BusinessDays = 1,
                            Description = "",
                            EndDate = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 2,
                            UserId = new Guid("84ad3fd0-1151-9e9a-71dc-3eaf99e4bdbb")
                        },
                        new
                        {
                            Id = new Guid("1e6ed0df-2f49-2f41-88da-77b17348a03e"),
                            BusinessDays = 4,
                            Description = "",
                            EndDate = new DateTime(2025, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Type = 1,
                            UserId = new Guid("1242bf85-0669-40ef-724b-eef922556dda")
                        },
                        new
                        {
                            Id = new Guid("40de25b3-8a46-9154-5442-acb43709e63e"),
                            BusinessDays = 5,
                            Description = "",
                            EndDate = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Type = 0,
                            UserId = new Guid("1242bf85-0669-40ef-724b-eef922556dda")
                        },
                        new
                        {
                            Id = new Guid("2418c289-887d-27b6-7033-d8acef5e94b4"),
                            BusinessDays = 3,
                            Description = "",
                            EndDate = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2024, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 2,
                            UserId = new Guid("1242bf85-0669-40ef-724b-eef922556dda")
                        },
                        new
                        {
                            Id = new Guid("df4ca9bc-2a84-3d48-cef6-af1e94ab3abf"),
                            BusinessDays = 3,
                            Description = "",
                            EndDate = new DateTime(2025, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 2,
                            UserId = new Guid("48d9ad4a-2f00-29d2-715f-8c6e02a191f7")
                        },
                        new
                        {
                            Id = new Guid("7f643d88-f6e7-c304-720e-6dae86fad544"),
                            BusinessDays = 4,
                            Description = "",
                            EndDate = new DateTime(2025, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Type = 2,
                            UserId = new Guid("48d9ad4a-2f00-29d2-715f-8c6e02a191f7")
                        },
                        new
                        {
                            Id = new Guid("2105129e-a021-0e81-42ce-a5f218b31df8"),
                            BusinessDays = 2,
                            Description = "",
                            EndDate = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2024, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 0,
                            UserId = new Guid("48d9ad4a-2f00-29d2-715f-8c6e02a191f7")
                        },
                        new
                        {
                            Id = new Guid("ea18c0d5-94fe-58bd-4044-5874ada6669b"),
                            BusinessDays = 2,
                            Description = "",
                            EndDate = new DateTime(2025, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 2,
                            UserId = new Guid("dbed805b-a6c2-4a54-534d-b61eff529976")
                        },
                        new
                        {
                            Id = new Guid("4925c542-7440-ae33-32cd-594be6e7d1c5"),
                            BusinessDays = 4,
                            Description = "",
                            EndDate = new DateTime(2025, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Type = 0,
                            UserId = new Guid("dbed805b-a6c2-4a54-534d-b61eff529976")
                        },
                        new
                        {
                            Id = new Guid("ec4fe716-5cd7-1838-3b82-216c071d4bf3"),
                            BusinessDays = 1,
                            Description = "",
                            EndDate = new DateTime(2024, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2024, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = 1,
                            UserId = new Guid("dbed805b-a6c2-4a54-534d-b61eff529976")
                        });
                });

            modelBuilder.Entity("HahnLeaveAbsenceManagement.Domain.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeavesLeft")
                        .HasColumnType("int");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e8b8f1f5-85a8-adb8-01a7-17783f381411"),
                            CreatedBy = new Guid("80161798-9708-1a26-fadd-41f994fb23d8"),
                            CreatedOn = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "amina.bennani@hahn.local",
                            FirstName = "Amina",
                            LastName = "Bennani",
                            LeavesLeft = 18,
                            Password = "$2a$10$7EqJtq98hPqEX7fNZaFWo.HWRHsGM68cVlfJgnEZJa3yDI//qK9pC",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("10ddb1bd-7956-9c97-a82b-28edd1c8ccd2"),
                            CreatedBy = new Guid("80161798-9708-1a26-fadd-41f994fb23d8"),
                            CreatedOn = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "youssef.elfassi@hahn.local",
                            FirstName = "Youssef",
                            LastName = "ElFassi",
                            LeavesLeft = 18,
                            Password = "$2a$10$7EqJtq98hPqEX7fNZaFWo.HWRHsGM68cVlfJgnEZJa3yDI//qK9pC",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("c298b7fb-4152-0102-2e7b-d22eef00e52d"),
                            CreatedBy = new Guid("80161798-9708-1a26-fadd-41f994fb23d8"),
                            CreatedOn = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sara.azli@hahn.local",
                            FirstName = "Sara",
                            LastName = "Azli",
                            LeavesLeft = 18,
                            Password = "$2a$10$7EqJtq98hPqEX7fNZaFWo.HWRHsGM68cVlfJgnEZJa3yDI//qK9pC",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("6998a4fe-7fc2-590e-616d-4ad24a81a6db"),
                            CreatedBy = new Guid("80161798-9708-1a26-fadd-41f994fb23d8"),
                            CreatedOn = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "omar.amrani@hahn.local",
                            FirstName = "Omar",
                            LastName = "Amrani",
                            LeavesLeft = 18,
                            Password = "$2a$10$7EqJtq98hPqEX7fNZaFWo.HWRHsGM68cVlfJgnEZJa3yDI//qK9pC",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("35a56cc6-18e2-2e49-3239-5c878db167bc"),
                            CreatedBy = new Guid("80161798-9708-1a26-fadd-41f994fb23d8"),
                            CreatedOn = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hajar.bouazza@hahn.local",
                            FirstName = "Hajar",
                            LastName = "Bouazza",
                            LeavesLeft = 18,
                            Password = "$2a$10$7EqJtq98hPqEX7fNZaFWo.HWRHsGM68cVlfJgnEZJa3yDI//qK9pC",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("901436a1-5810-6631-74fd-382120a6441b"),
                            CreatedBy = new Guid("80161798-9708-1a26-fadd-41f994fb23d8"),
                            CreatedOn = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "reda.elidrissi@hahn.local",
                            FirstName = "Reda",
                            LastName = "ElIdrissi",
                            LeavesLeft = 18,
                            Password = "$2a$10$7EqJtq98hPqEX7fNZaFWo.HWRHsGM68cVlfJgnEZJa3yDI//qK9pC",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("5815c2a8-ad8d-03a6-a265-18f65c4882cc"),
                            CreatedBy = new Guid("80161798-9708-1a26-fadd-41f994fb23d8"),
                            CreatedOn = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nadia.zerhouni@hahn.local",
                            FirstName = "Nadia",
                            LastName = "Zerhouni",
                            LeavesLeft = 18,
                            Password = "$2a$10$7EqJtq98hPqEX7fNZaFWo.HWRHsGM68cVlfJgnEZJa3yDI//qK9pC",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("8e91a67b-8c05-e6b5-8801-02477295103f"),
                            CreatedBy = new Guid("80161798-9708-1a26-fadd-41f994fb23d8"),
                            CreatedOn = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "adil.tazi@hahn.local",
                            FirstName = "Adil",
                            LastName = "Tazi",
                            LeavesLeft = 18,
                            Password = "$2a$10$7EqJtq98hPqEX7fNZaFWo.HWRHsGM68cVlfJgnEZJa3yDI//qK9pC",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("46199b05-5208-7a6e-96a1-b1fa675af8aa"),
                            CreatedBy = new Guid("80161798-9708-1a26-fadd-41f994fb23d8"),
                            CreatedOn = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "meriem.elmalki@hahn.local",
                            FirstName = "Meriem",
                            LastName = "ElMalki",
                            LeavesLeft = 18,
                            Password = "$2a$10$7EqJtq98hPqEX7fNZaFWo.HWRHsGM68cVlfJgnEZJa3yDI//qK9pC",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("ed667da6-b4f7-3881-3cd6-96c44c15e821"),
                            CreatedBy = new Guid("80161798-9708-1a26-fadd-41f994fb23d8"),
                            CreatedOn = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "karim.chafik@hahn.local",
                            FirstName = "Karim",
                            LastName = "Chafik",
                            LeavesLeft = 18,
                            Password = "$2a$10$7EqJtq98hPqEX7fNZaFWo.HWRHsGM68cVlfJgnEZJa3yDI//qK9pC",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("75b52741-41e2-640a-cac3-2a2a63457b4e"),
                            CreatedBy = new Guid("80161798-9708-1a26-fadd-41f994fb23d8"),
                            CreatedOn = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "salma.alaoui@hahn.local",
                            FirstName = "Salma",
                            LastName = "Alaoui",
                            LeavesLeft = 18,
                            Password = "$2a$10$7EqJtq98hPqEX7fNZaFWo.HWRHsGM68cVlfJgnEZJa3yDI//qK9pC",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("84ad3fd0-1151-9e9a-71dc-3eaf99e4bdbb"),
                            CreatedBy = new Guid("80161798-9708-1a26-fadd-41f994fb23d8"),
                            CreatedOn = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "yassin.berrada@hahn.local",
                            FirstName = "Yassin",
                            LastName = "Berrada",
                            LeavesLeft = 18,
                            Password = "$2a$10$7EqJtq98hPqEX7fNZaFWo.HWRHsGM68cVlfJgnEZJa3yDI//qK9pC",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("1242bf85-0669-40ef-724b-eef922556dda"),
                            CreatedBy = new Guid("80161798-9708-1a26-fadd-41f994fb23d8"),
                            CreatedOn = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "imane.mouline@hahn.local",
                            FirstName = "Imane",
                            LastName = "Mouline",
                            LeavesLeft = 18,
                            Password = "$2a$10$7EqJtq98hPqEX7fNZaFWo.HWRHsGM68cVlfJgnEZJa3yDI//qK9pC",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("48d9ad4a-2f00-29d2-715f-8c6e02a191f7"),
                            CreatedBy = new Guid("80161798-9708-1a26-fadd-41f994fb23d8"),
                            CreatedOn = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "anas.jebbar@hahn.local",
                            FirstName = "Anas",
                            LastName = "Jebbar",
                            LeavesLeft = 18,
                            Password = "$2a$10$7EqJtq98hPqEX7fNZaFWo.HWRHsGM68cVlfJgnEZJa3yDI//qK9pC",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("dbed805b-a6c2-4a54-534d-b61eff529976"),
                            CreatedBy = new Guid("80161798-9708-1a26-fadd-41f994fb23d8"),
                            CreatedOn = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lina.farissi@hahn.local",
                            FirstName = "Lina",
                            LastName = "Farissi",
                            LeavesLeft = 18,
                            Password = "$2a$10$7EqJtq98hPqEX7fNZaFWo.HWRHsGM68cVlfJgnEZJa3yDI//qK9pC",
                            Role = 1
                        });
                });

            modelBuilder.Entity("HahnLeaveAbsenceManagement.Domain.LeaveRequest.LeaveRequest", b =>
                {
                    b.HasOne("HahnLeaveAbsenceManagement.Domain.User.User", "User")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HahnLeaveAbsenceManagement.Domain.User.User", b =>
                {
                    b.Navigation("LeaveRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
